import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "./component/Header";
import About from "./component/About";
import Occassion from "./component/Occassions";
import Service from "./component/Service";
import Gallery from "./component/Gallery";
import Footer from "./component/Footer";
import Main from "./component/Main";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>A2Z Balloon Decoration</title>
        <meta
          name="description"
          content="Generated by A2Z balooan decoration"
        />
        <meta name="google-site-verification" content="ZRlr5BDsmx55krhaL5ophvQtuYL1mIi1n7OjQidomdM" />
        <meta name="robots" content="index, follow"></meta>
        <meta name="robots" content="max-image-preview:large"/> 
        <meta name="robots" content="<max-snippet:-1/>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <div className="container mx-auto">
        <Header />
        <Main />
        <About />
        <Occassion />
        <Service />
        <Gallery />
        <Footer />
      </div>
    </>
  );
}
